name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # or change this if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # If you have a build process (e.g. building with a static site generator),
      # you’d add those steps here. Since you have static index.html, we may skip build.
      # EXAMPLE (if using e.g. some build tool):
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.x"
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      # - name: Run tests
      #   run: pytest

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The directory to publish, relative to repository root:
          publish_dir: ./  # root of repo, since index.html is at root
          # you may want to exclude files you don’t want published
          # optionally set a custom commit message
          commit_message: Deploy from GitHub Actions

